excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://SamYap.github.io
title: The Stealthy Hobo's Ultra-Cheap Travel Blog
tagline: Global adventure and exploration for all
description: Ideas and itineraries for exploring the world, one piece at a time, on a tight budget. 
paginate: 5